### PR TITLE
Update import to fix deprecation warning

### LINKED ISSUE #6: Deprecation warning in console
When running the main command the following warning appears:

```sh
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```

### PR DESCRIPTION
**Pull request by cvburgess**
Closes #6

### CODE REVIEW

**Comment by cvburgess** [comment]
Any plans to merge this or should I close @kimmelsg

**Comment by eknowlton** [comment]
Looks good @cvburgess

Thanks for taking the time to update this.

**Comment by eknowlton** [comment]
We don't actually use this or update this repository any more. We're considering archiving it.

**Comment by jamtur01** [comment]
@eknowlton Maybe ping the folks at Clubhouse? They might have a desire to take it over?

**Comment by cvburgess** [comment]
If not, I would be happy to as well :D

**Comment by eknowlton** [comment]
Will be happy to transfer this repo to you.

**Comment by eknowlton** [comment]
If you delete your fork ( maybe rename ? ) we can transfer it to you. Otherwise we just want to archive this.

**Pull request merged**
